name: Cache
description: Restore and Save directories using a cache key
author: https://github.com/danthorpe
requirements:
  - aws
configuration:
  properties:
    save_paths:
        type: [ string, array ]
    save_key:
        type: string
    restore:
        type: [ string, array ]
  oneOf:
    - required:
      - save_paths
      - save_key
    - required:
      - restore
  additionalProperties: false