name: Cache
description: Restore and Save directories using a cache key
author: https://github.com/danthorpe
requirements:
  - aws
configuration:
  properties:
    cache_key:
        type: string
    paths:
        type: [ string, array ]
  required:
    - cache_key
    -paths
  additionalProperties: false